name: Sync

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: "https://github.com/papwuj/papwuj.github.io.git"
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: "https://papwuj:7d0c55c3bbea4241d4a228ef32736443@gitee.com/papwuj/papwuj.git"

    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@master
      with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: papwuj
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          # gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-password: 7d0c55c3bbea4241d4a228ef32736443
          # 注意替换为你的 Gitee 仓库
          gitee-repo: papwuj/papwuj