name: WIKI CI/CD

# 触发条件：在 push 到 hexo-blog-backup 分支后触发
on:
  push:
    branches: 
      - main

env:
  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Setup node
      # 设置 node.js 环境
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'

    - name: Cache node modules
      # 设置包缓存目录，避免每次下载
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install hexo dependencies
      # 下载 hexo-cli 脚手架及相关安装包
      run: |
        npm install -g hexo-cli
        npm install

    - name: Generate files
      # 编译 markdown 文件
      run: |
        hexo clean
        hexo generate

    - name: Deploy hexo blog
      env: 
        # Github 仓库
        GITHUB_REPO: github.com/papwuj/papwuj.github.io.git
        # Coding 仓库
        CODING_REPO: e.coding.net/papwuj/blogs.git
        # Gitee 仓库
        GITEE_REPO: gitee.com/papwuj/papwuj.gitee.io.git
      # 将编译后的博客文件推送到指定仓库
      # 
      run: |
        git config --global user.name "WuJing"
        git config --global user.email "wujing0510@live.com"
        git config --global init.defaultBranch main
        git config --global --add push.autoSetupRemote true
        mkdir ~/.ssh/
        echo "-----BEGIN OPENSSH PRIVATE KEY-----" >> ~/.ssh/id_deploy
        echo "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW" >> ~/.ssh/id_deploy
        echo "QyNTUxOQAAACD+VmFsUAxzXoQeUdLYph39pCmVTphROH4vz5pFHppPtQAAAJjA/rLmwP6y" >> ~/.ssh/id_deploy
        echo "5gAAAAtzc2gtZWQyNTUxOQAAACD+VmFsUAxzXoQeUdLYph39pCmVTphROH4vz5pFHppPtQ" >> ~/.ssh/id_deploy
        echo "AAAECuayTko/B3pUrawI1fnSYjCF7qCTteksNvs9SRfp75Ov5WYWxQDHNehB5R0timHf2k" >> ~/.ssh/id_deploy
        echo "KZVOmFE4fi/PmkUemk+1AAAAE3d1amluZzA1MTBAbGl2ZS5jb20BAg==" >> ~/.ssh/id_deploy
        echo "-----END OPENSSH PRIVATE KEY-----" >> ~/.ssh/id_deploy
        cd ./public && git init && git add .
        git branch -m gh-pages
        git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "git@github.com:papwuj/papwuj.github.io.git"